server:
  port: 8989

spring:
  jmx:
    default-domain: test
  datasource:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    type: com.alibaba.druid.pool.DruidDataSource