server:
  port: 8989

spring:
  jmx:
    default-domain: dev
  datasource:
    username: root
    password: Yuntian_0210
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.170.100/yun_erp
    type: com.alibaba.druid.pool.DruidDataSource